import type { Metadata } from "next";

import "../styles/component.css";
import "../styles/globals.css";
import "../styles/fonts.css";
import Header from "./Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className=" relative">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
